services:
  # 1. 全局网关代理
  nginx:
    image: nginx:alpine
    container_name: blog_nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      # 用相对路径挂载你刚改好的 nginx.conf
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      # 从前端容器的命名共享卷里读静态网页产物
      - frontend_dist:/usr/share/nginx/html:ro
    depends_on:
      - frontend
      - backend

  # 2. 前端编译器
  frontend:
    image: crpi-hpnvugd276r767na.cn-hangzhou.personal.cr.aliyuncs.com/fyuo-blog/blog-frontend:latest
    container_name: blog-frontend
    restart: always
    volumes:
      - frontend_dist:/app/dist

  # 3. 后端 Go-Gin 服务
  backend:
    image: crpi-hpnvugd276r767na.cn-hangzhou.personal.cr.aliyuncs.com/fyuo-blog/blog-backend:latest
    container_name: blog-backend
    restart: always
    expose:
      - "8080" # 安全隐藏，拒绝公网直连
    env_file:
      - ./.env # 动态读取当前 data 目录下的加密环境文件
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  # 4. 缓存层 Redis
  redis:
    image: redis:8-alpine
    container_name: blog_redis
    restart: always
    ports:
      - "127.0.0.1:6380:6379" # 仅限宿主机回环调用本地安全
    volumes:
      - redis_data:/var/lib/redis/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10

  # 5. 存储层 PostgreSQL
  postgres:
    image: postgres:16-alpine
    container_name: blog_postgres
    restart: always
    env_file:
      - ./.env # 让数据库服务直接从你的 .env 里抽离密码
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      TZ: Asia/Shanghai
    ports:
      - "127.0.0.1:5432:5432" # 隐藏端口
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d ${DB_NAME}"]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  redis_data:
  postgres_data:
  frontend_dist:
