server {
    listen 80;
    server_name fyuoblog.top www.fyuoblog.top; # 顺便加上 www 泛解析支持
    # listen 8888;
    # server_name _; # 顺便加上 www 泛解析支持


    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml;

    # 1. 前端静态资源托管
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html; # 完美支持 React Router History 模式
    }

    # 2. 后端 Gin 接口反向代理
    location /api/ {
        proxy_pass http://backend:8080; # 注意末尾有斜杠，会将 /api/ 剥离后再转发给 Gin
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}