Server:
  host: "127.0.0.1"
  port: 8090
  mode: "test"  #gin 运行模式: debug | release | test

database:
  host: "127.0.0.1"
  port: 5432
  user: "root"
  password: "97224224"
  dbname: "myblog"
  sslmode: "disable"
  timezone: "Asia/Shanghai"
  # --- 连接池配置 ---
  max_idle_conns: 10              # 最大空闲连接数
  max_open_conns: 100             # 最大打开连接数
  conn_max_lifetime: 3600         # 连接最大存活时间（单位：秒，建议用纯数字在代码里转时间）

redis:
  host: "127.0.0.1"
  port: 6380
  password: ""
  db: 0
  pool_size: 100                   # 连接池大小
  query_timeout: 2s                # 单次 Redis 操作超时
